### ISSUE TITLE
Missing tags in public note

### ISSUE THREAD

**Issue by arneschween** [jrc-dev/nostr-potatoes#1]
When one sends out a public note for a movie review using hashtags as in note1k4gxcaef43cnqdrem9906jmfnf2unxhusgyjspftqrkkgd3fykrsrgfqqs NostrPotatoes does not include the tags in the note - even not the #NostrPotatoes tag, so the note cannot be find by clients easily. 
Also see https://github.com/hzrd149/nostrudel/issues/16#issuecomment-1727833933

**Comment by jrc-dev** [comment]
Fixed

**Comment by jrc-dev** [comment]
Thank you! I fix this!
